#!/bin/bash

########################################################
## Randomly change background image using gsettings
########################################################

# Interval (in seconds) for changing the background image
INTERVAL=${INTERVAL:-120}

# The display mode to use
# One of: wallpaper, centered, scaled, stretched, zoom, spanned
MODE=${MODE:-zoom}

RECURSIVE=true

if [ $# -eq 0 ]; then
  echo "  Usage: $0 [<directory> | <file>] ..."
  exit
fi

# Set interval to 0 if there is only one argument and it is a file
if [[ $# -eq 1 && -f $1 ]]; then
    INTERVAL=0
fi

# Function that sets $1 as background using gsettings
function set_background
{
  FILE="$1"
  echo Setting background: $FILE

  # Set the background
  gsettings set org.gnome.desktop.background picture-uri-dark file://$FILE
  gsettings set org.gnome.desktop.background picture-uri file://$FILE

  # Set the display mode
  gsettings set org.gnome.desktop.background picture-options $MODE
}

# Function that calls set_background for all images found in $1
function process_directory
{
  # Find images and randomize order
  if $RECURSIVE; then
    DEPTH=""
  else
    DEPTH="-maxdepth 1"
  fi
  FILES=$(find $1 $DEPTH -type f \( -iname \*.jpeg -o -iname \*.jpg -o -iname \*.png -o -iname \*.bmp \) | sort -R)
  
  OIFS="$IFS"
  IFS=$'\n'
  for FILE in $FILES;
  do
    set_background $FILE
    sleep $INTERVAL
  done
  IFS="$OIFS"
}

for ARGUMENT in "$@"
do
  if [ -f $ARGUMENT ]; then
    set_background "$ARGUMENT"
    sleep $INTERVAL
  fi
  if [ -d $ARGUMENT ]; then
    process_directory "$ARGUMENT"
  fi
done
